const getAutoGeneratePassword = () => {
  const maxLength = 20;
  const minLength = 12;

  // パスワードに使用可能な文字を決定（今回はアルファベットの大文字と小文字 ＋ 数字 ＋ symbolsの記号）
  const lowerCase = 'abcdefghijklmnopqrstuvwxyz';
  const upperCase = lowerCase.toLocaleUpperCase();
  const numbers = '0123456789';
  const symbols = '%&$#()';
  const chars = lowerCase + upperCase + numbers + symbols;

  // パスワードが持つ文字列条件を正規表現で追加（今回はアルファベット小文字1つ以上かつ数字1つ以上）
  const lowerCaseRegex = /[a-z]/;
  const numberRegex = /[0-9]/;

  // autoGeneratedPasswordが以上の条件を満たせばvalidがtrueになる
  let valid = false;
  let autoGeneratedPassword = '';

  while (!valid) {
    autoGeneratedPassword = '';
    // パスワードの文字数を上で決めた範囲内でランダムに決定
    const randomLength =
      Math.floor(Math.random() * (maxLength - minLength)) + minLength;
    while (autoGeneratedPassword.length < randomLength) {
      // 上で決定したcharsの中からランダムに1文字ずつ追加
      const index = Math.floor(Math.random() * chars.length);
      autoGeneratedPassword += chars[index];
    }

    // パスワードが上で決定した条件をすべて満たしているかチェック
    // 条件を満たすまでループ
    valid =
      minLength <= autoGeneratedPassword.length &&
      autoGeneratedPassword.length <= maxLength &&
      lowerCaseRegex.test(autoGeneratedPassword) &&
      numberRegex.test(autoGeneratedPassword);
  }

  return autoGeneratedPassword;
};

export default getAutoGeneratePassword;
